---
- name: Install homebrew
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Install Homebrew
      become: true
      become_method: sudo
      become_user: root
      become_flags: '-H'
      shell: xcode-select --install
      # shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      register: command_output

    - name: Display Stdout
      debug:
        var: command_output.stdout
