name: Test on OSX

on:
  push:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: install dependencies
        run: pip3 install ansible

      - name: run ansible playbook
        run: python3 -m ansible-playbook ansible/playbook.yml
